RPPP21APP/Models/Worker.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
namespace RPPP21APP.Models;

public partial class Worker
{
    public int WorkerId { get; set; }

    [Column(TypeName = "varchar(40)")]
    public string Name { get; set; } = null!;
    [Column(TypeName = "varchar(40)")]
    public string Surname { get; set; } = null!;

    public double Salary { get; set; }

    public string PhoneNumber { get; set; } = null!;

    public string Experience { get; set; } = null!;

    public double? WorkingHours { get; set; }

    public virtual ICollection<ActionOnGroup> ActionOnGroups { get; } = new List<ActionOnGroup>();
}

RPPP21APP/Controllers/WorkersController.cs
using Azure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.VisualBasic;
using NuGet.Protocol.Core.Types;
using RPPP21APP.Data;
using RPPP21APP.Interfaces;
using RPPP21APP.Models;
using RPPP21APP.Repositories;
using RPPP21APP.Repository;
using RPPP21APP.ViewModels;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Net;
using static System.Reflection.Metadata.BlobBuilder;

namespace RPPP21APP.Controllers
{
    public class WorkersController : Controller
    {
        
        private readonly IWorkerRepository _workerRepository;
        private readonly AppSettings _appSettings;

        public WorkersController(IWorkerRepository workerRepository, IOptionsSnapshot<AppSettings> options)
        {
            _workerRepository = workerRepository;
            _appSettings = options.Value;
        }

        // GET: Worker
        public async Task<IActionResult> Index(int page = 1, int sort = 1, bool ascending = true)
        {
            int pagesize = _appSettings.PageSize;

            int count = await _workerRepository.GetCountAsync();

            var pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                Sort = sort,
                Ascending = ascending,
                ItemsPerPage = pagesize,
                TotalItems = count
            };
            if (page < 1 || page > pagingInfo.TotalPages)
            {
                return RedirectToAction(nameof(Index), new { page = 1, sort, ascending });
            }         

            var workers = await _workerRepository.GetSliceAsync((page - 1) * pagesize, pagesize);

            var workerViewModel = new IndexWorkerViewModel
            {
                Workers = workers,
                Page = page,
                PageSize = pagesize,
                TotalWorkers = count,
                TotalPages = (int)Math.Ceiling(count / (double)pagesize),
                
            };

            return View(workerViewModel);

        }

        // GET: Worker/Details/5
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var worker = await _workerRepository.GetByIdAsync(id.Value);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }


        // GET: WorkersController/Create
        // GET: Worker/Create

        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: WorkersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateWorkerViewModel workerVM)
        {
            if (!ModelState.IsValid)
            {
                return View("Create");
            }

            var worker = new Worker
            {
                Name = workerVM.Name,
                Surname = workerVM.Surname,
                Salary = workerVM.Salary,
                PhoneNumber = workerVM.PhoneNumber,
                Experience = workerVM.Experience,
                WorkingHours = workerVM.WorkingHours,
            };

            try
            {
                _workerRepository.Add(worker);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: WorkersController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var worker = await _workerRepository.GetByIdAsync(id);

            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // POST: WorkersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, CreateWorkerViewModel workerVM)
        {

            if (!ModelState.IsValid)
            {
                return View("Edit");
            }
            
            var worker = await _workerRepository.GetByIdAsync(id);
            if (worker == null)
            {
                return NotFound();
            }
            try
            {
                // Update worker with values from view model
                worker.Name = workerVM.Name;
                worker.Surname = workerVM.Surname;
                worker.Salary = workerVM.Salary;
                worker.PhoneNumber = workerVM.PhoneNumber;
                worker.Experience = workerVM.Experience;
                worker.WorkingHours = workerVM.WorkingHours;

                _workerRepository.Update(worker);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }




        // GET: WorkersController/Delete/5
        // GET: WorkersController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var worker = await _workerRepository.GetByIdAsync(id);
            if (worker == null)
            {
                return NotFound();
            }

            return View(worker);
        }

        // POST: WorkersController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var worker = await _workerRepository.GetByIdAsync(id);
            _workerRepository.Delete(worker);
            _workerRepository.Save();
            return RedirectToAction(nameof(Index));
        }
    }
}

RPPP21APP/Views/Workers/Create.cshtml
@model RPPP21APP.Models.Worker

@{
    ViewData["Title"] = "Create";
}

<h1>Create new worker</h1>

<h4>Fill details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkingHours" class="control-label"></label>
                <input asp-for="WorkingHours" class="form-control" />
                <span asp-validation-for="WorkingHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Workers" asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RPPP21APP/Views/Workers/Delete.cshtml
@model RPPP21APP.Models.Worker

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Worker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Experience)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Experience)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkingHours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkingHours)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="WorkerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RPPP21APP/Views/Workers/Detail.cshtml
@model RPPP21APP.Models.Worker

@{
    ViewData["Title"] = "Details";
}

<h1>Worker Details</h1>

<div class="p-1 mb-2 rounded-3">
    <div class="container-fluid py-5">
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Surname)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Surname)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Salary)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Salary)
            </dd>
            <dt class="col-sm-4">
                Phone number
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Experience)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Experience)
            </dd>
            <dt class="col-sm-4">
                Working hours
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WorkingHours)
            </dd>
        </dl>
        <a asp-action="Index" class="btn btn-secondary mr-2">Back to List</a>
    </div>
</div>

RPPP21APP/Views/Workers/Edit.cshtml
@model RPPP21APP.Models.Worker

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Worker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="WorkerId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkingHours" class="control-label"></label>
                <input asp-for="WorkingHours" class="form-control" />
                <span asp-validation-for="WorkingHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Workers" asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RPPP21APP/Views/Workers/Index.cshtml
@using RPPP21APP.ViewModels;
@model IndexWorkerViewModel

@{
    ViewData["Title"] = "Index";
}

@{
    bool isAuthenticated = User.Identity?.IsAuthenticated == true;

    int resultStart = ((Model.Page - 1) * Model.PageSize) + 1;
    int resultEnd = Math.Min(resultStart + Model.PageSize - 1, Model.TotalWorkers);

    bool isValidPage = resultStart <= Model.TotalWorkers;

    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<h1>Workers</h1>


<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            @if (isValidPage)
            {
                <a type="button" class="btn btn-sm btn-primary @prevDisabled"
               asp-action="Index" asp-route-page="@(Model.Page - 1)">
                    Prev
                </a>
                <a type="button" class="btn btn-sm btn-primary @nextDisabled"
               asp-action="Index" asp-route-page="@(Model.Page + 1)">
                    Next
                </a>
                <span class="text-muted text-small">Results @resultStart - @resultEnd of @Model.TotalWorkers</span>
            }
    </div>
</div>

<div class="table-responsive">
<table class="table table-hover table-dark" id="tbl_exporttable_to_xls">
    <thead>
        <tr>
            <th scope="col">
                        @Html.DisplayNameFor(model => Model.Workers.FirstOrDefault().Name)
            </th>
            <th scope="col">
                        @Html.DisplayNameFor(model => Model.Workers.FirstOrDefault().Surname)
            </th>
            <th scope="col">
                        @Html.DisplayNameFor(model => Model.Workers.FirstOrDefault().Salary)
            </th>
            <th scope="col">
                        @Html.DisplayNameFor(model => Model.Workers.FirstOrDefault().PhoneNumber)
            </th>
            <th scope="col">
                        @Html.DisplayNameFor(model => Model.Workers.FirstOrDefault().Experience)
            </th>
            <th scope="col">
                        @Html.DisplayNameFor(model => Model.Workers.FirstOrDefault().WorkingHours)
            </th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Workers) {
        <tr>
            <td scope="row">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Experience)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkingHours)
            </td>
            <td>
                    <a asp-action="Detail" asp-route-id="@item.WorkerId" class="btn btn-secondary">Details</a>
                    <a asp-action="Edit" asp-route-id="@item.WorkerId" class="btn btn-secondary mr-2">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.WorkerId" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>