RPPP21APP/Models/Plot.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP21APP.Models;

public partial class Plot
{
    public string? Name { get; set; }
    public string? Coordinates { get; set; }
    public double? Area { get; set; }   
    public int PlotId { get; set; }
    public int WeatherConditionsId { get; set; }
    public virtual ICollection<GroupsOnPlot> GroupsOnPlots { get; } = new List<GroupsOnPlot>();

    public virtual ICollection<Infrastructure> Infrastructures { get; } = new List<Infrastructure>();

    public virtual ICollection<Lease> Leases { get; } = new List<Lease>();

    public virtual ICollection<PlotDelivery> PlotDeliveries { get; } = new List<PlotDelivery>();

    public virtual ICollection<Storage> Storages { get; } = new List<Storage>();
    public virtual WeatherCondition WeatherConditions { get; set; } = null!;
}

RPPP21APP/Controllers/PlotController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RPPP21APP.Data;
using RPPP21APP.Interfaces;
using RPPP21APP.Models;
using RPPP21APP.Repositories;
using RPPP21APP.Repository;
using RPPP21APP.ViewModels;
using System.Collections.Generic;
using System.Net;


namespace RPPP21APP.Controllers
{
    public class PlotController : Controller
    {

        private readonly IPlotRepository _plotRepository;
        private readonly IWeatherConditionsRepository _weatherConditionsRepository;

        public PlotController(IPlotRepository plotRepository, IWeatherConditionsRepository weatherConditionsRepository)
        {
            _plotRepository = plotRepository;
            _weatherConditionsRepository = weatherConditionsRepository;
        }
        public async Task<IActionResult> Index()
        {          
                var model = await _plotRepository.GetAll();
                return View(model);            
        }

        [HttpGet]
        [Route("Plot/Create")]
        public async Task<IActionResult> Create()
        {
            CreatePlotViewModel plotVM = new CreatePlotViewModel()
            {
                WeatherConditions = await _weatherConditionsRepository.GetAll()
            };
            return View(plotVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePlotViewModel plotVM)
        {
            /*if (!ModelState.IsValid)
            {
                plotVM.WeatherConditions = await _weatherConditionsRepository.GetAll();
                return View("Create");
            }*/

            var plot = new Plot
            {
                Name = plotVM.Name,
                Coordinates = plotVM.Coordinates,
                Area = plotVM.Area,
                WeatherConditionsId = plotVM.WeatherConditionsId,
            };

            _plotRepository.Add(plot);               
            return RedirectToAction("Index");           
        }

        [HttpGet]
        [Route("Plot/Edit/{Id}")]
        public async Task<IActionResult> Edit(int id)
        {           
                var plot = await _plotRepository.GetByIdAsync(id);
                if (plot == null) return View("Error");
                var plotVM = new CreatePlotViewModel
                {
                    Name = plot.Name,
                    Coordinates = plot.Coordinates,
                    Area = plot.Area,
                    WeatherConditionsId = plot.WeatherConditionsId,
                    WeatherConditions = await _weatherConditionsRepository.GetAll()
                };
                return View(plotVM);           
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CreatePlotViewModel plotVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit plot");
                return View("Edit", plotVM);
            }

            var plot = new Plot
            {
                Name = plotVM.Name,
                Coordinates = plotVM.Coordinates,
                Area = plotVM.Area,
                WeatherConditionsId = plotVM.WeatherConditionsId,
                PlotId = id,
                WeatherConditions = await _weatherConditionsRepository.GetByIdAsync(id),
            };
           
            var entity = await _plotRepository.GetByIdAsyncNoTrack(id);
            if (entity == null) return View("Error");
            _plotRepository.Update(plot);               
            //context.Entry(entity).Property(x => x.PlotId).IsModified = false; //Maybe necessary for safety??
            //context.Entry(entity).CurrentValues.SetValues(plot);                
            //context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Plot/{Id}")]
        public async Task<IActionResult> Detail(int id)
        {
            using (var context = new ApplicationDbContext())
            {               
                var plot = await context.Plots.Include(x => x.Infrastructures)
                    .Include(x => x.GroupsOnPlots)
                        .ThenInclude(x => x.GroupOfPlants)
                            .ThenInclude(x => x.PlantType)
                                
                    .Include(x => x.GroupsOnPlots)
                        .ThenInclude(x => x.GroupOfPlants)
                            .ThenInclude(x => x.Plants)

                    .Include(x => x.WeatherConditions)

                    .AsNoTracking()
                    .FirstOrDefaultAsync(x => x.PlotId == id);

                return View(plot);
            }
        }

        public async Task<ActionResult> Delete(int id)
        {
            // Get the object with the given id
            var plot = await _plotRepository.GetByIdAsync(id);
            if (plot == null)
            {
                // If the infrastructure object is not found, return a 404 error
                return NotFound();
            }

            // Pass the infrastructure object to the view
            return View(plot);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            // Get the infrastructure object with the given id
            var plot = await _plotRepository.GetByIdAsync(id);
            if (plot == null)
            {
                // If the infrastructure object is not found, return a 404 error
                return NotFound();
            }

            // Delete the object from the database
            _plotRepository.Delete(plot);
            // Redirect to the index page

            // Otherwise, redirect to the Index action in the current controller
            return RedirectToAction("Index");

        }
    }
}

RPPP21APP/Views/Plot/Create.cshtml
@using RPPP21APP.ViewModels;
@model CreatePlotViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-action="Create" enctype="multipart/form-data">
    
    <div class="form-group" style="margin-top:90px">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" aria-describedby="emailHelp" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Coordinates">Coordinates</label>
        <input asp-for="Coordinates" class="form-control" aria-describedby="emailHelp" placeholder="Coordinates">
        <span asp-validation-for="Coordinates" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Area">Area</label>
        <input asp-for="Area" class="form-control" aria-describedby="emailHelp" placeholder="Image">
        <span asp-validation-for="Area" class="text-danger"></span>
    </div>
    <div class="form group">
        <label asp-for="WeatherConditionsId">Weather Condition</label>
        <select asp-for="WeatherConditionsId" asp-items="@(new SelectList(Model.WeatherConditions, "WeatherConditionsId","SunLevel"))" class="form-control form-control">
            <option>Please select one</option>
    </select>
        <span asp-validation-for="WeatherConditions" class="text-danger"></span>
        
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

RPPP21APP/Views/Plot/Delete.cshtml
@model Plot

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>

<div class="p-1 mb-2 rounded-3">
    <div class="container-fluid py-5">
        <h2>Plot @Html.DisplayFor(model => model.Name)</h2>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Coordinates)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Coordinates)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Area)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Area)
            </dd>
            <dt class="col-sm-2">
                Sun level
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WeatherConditions.SunLevel)
            </dd>
            <dt class="col-sm-2">
                Water level
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WeatherConditions.WaterLevel)
            </dd>
        </dl>
    </div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="PlotId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RPPP21APP/Views/Plot/Detail.cshtml
@model Plot
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="p-1 mb-2 rounded-3">
    <div class="container-fluid py-5">
        <h2>Plot @Html.DisplayFor(model => model.Name)</h2>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Coordinates)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Coordinates)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Area)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Area)
            </dd>
            <dt class="col-sm-2">
                Sun level
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WeatherConditions.SunLevel)
            </dd>
            <dt class="col-sm-2">               
                Water level
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WeatherConditions.WaterLevel)           
            </dd>          
        </dl>
    </div>
</div>

<h2>Infrastructure</h2>
<div class="table-responsive">
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Infrastructures.FirstOrDefault().Name)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Infrastructures.FirstOrDefault().BuildDate)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Infrastructures.FirstOrDefault().Cost)
                </th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Infrastructures)
            {
                <tr>
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BuildDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                    <td>                       
                        <a asp-controller="Infrastructure" asp-action="Edit" asp-route-id="@item.InfrastructureId" class="btn btn-secondary mr-2">Edit</a>
                        <a asp-controller="Infrastructure" asp-action="Delete" asp-route-id="@item.InfrastructureId" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
</br>
<button onclick="ExportToExcel('xlsx')" class="btn btn-warning">Export table to excel</button>
</br>
<h2>Plants</h2>
<div class="table-responsive">
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">
                
                    @Html.DisplayNameFor(model => model.GroupsOnPlots.FirstOrDefault().GroupOfPlants.FirstOrDefault().PlantType.Type)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.GroupsOnPlots.FirstOrDefault().GroupOfPlants.FirstOrDefault().Plants.FirstOrDefault().Name)
                <th scope="col">
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.GroupsOnPlots)
            {
                @foreach (var item2 in item.GroupOfPlants)
                {
                    @foreach (var item3 in item2.Plants)
                    {
                        <tr>
                            <td scope="row">
                                @Html.DisplayFor(modelItem => item2.PlantType.Type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item3.Name)
                            </td>                         
                           <td>
                            
                                <a asp-controller="Passport" asp-action="Details" asp-route-id="@item3.PassportId" class="btn btn-secondary mr-2">Passport</a>
                                <a asp-controller="GroupOfPlants" asp-action="Delete" asp-route-id="@item.PlotId" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>
</br>
<button onclick="ExportToExcel('xlsx')" class="btn btn-warning">Export table to excel</button>
<!--FOR DOWNLOADING TO EXCEL-->
<table class="table" id="export" align="center" style="display: none;">
    <thead>
        <tr>
             <th>
                @Html.DisplayNameFor(model => model.Infrastructures.FirstOrDefault().Name)
             </th>
             <th>
                @Html.DisplayNameFor(model => model.Infrastructures.FirstOrDefault().BuildDate)
             </th>
             <th>
                @Html.DisplayNameFor(model => model.Infrastructures.FirstOrDefault().Cost)
             </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Infrastructures)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BuildDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
            </tr>   
        }
    </tbody>
</table>



<table class="table" id="export" align="center" style="display: none;">
    <thead>
        <tr>
             <th>
                @Html.DisplayNameFor(model => model.GroupsOnPlots.FirstOrDefault().GroupOfPlants.FirstOrDefault().PlantType.Type)
             </th>
             <th>
                @Html.DisplayNameFor(model => model.GroupsOnPlots.FirstOrDefault().GroupOfPlants.FirstOrDefault().Plants.FirstOrDefault().Name)
             </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.GroupsOnPlots)
        {
            @foreach (var item2 in item.GroupOfPlants)
            {
                @foreach (var item3 in item2.Plants)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item2.PlantType.Type)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item3.Name)
                        </td>               
                    </tr>
                }
            }
        }
    </tbody>
</table>

RPPP21APP/Views/Plot/Edit.cshtml
@using RPPP21APP.Data;
@using RPPP21APP.ViewModels;
@model CreatePlotViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-action="Edit" enctype="multipart/form-data">

    <div class="form-group" style="margin-top:90px">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" aria-describedby="emailHelp" placeholder="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Coordinates">Coordinates</label>
        <input asp-for="Coordinates" class="form-control" aria-describedby="emailHelp" placeholder="Coordinates">
        <span asp-validation-for="Coordinates" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Area">Area</label>
        <input asp-for="Area" class="form-control" aria-describedby="emailHelp" placeholder="Image">
        <span asp-validation-for="Area" class="text-danger"></span>
    </div>
    <div class="form group">
        <label asp-for="WeatherConditionsId">WeatherCondition</label>
        <select asp-for="WeatherConditionsId" asp-items="@(new SelectList(Model.WeatherConditions, "WeatherConditionsId","SunLevel"))" class="form-control form-control">
            <option>Please select one</option>
        </select>
        <span asp-validation-for="WeatherConditions" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

RPPP21APP/Views/Plot/Index.cshtml
@model IEnumerable<Plot>



<h1>Plots</h1>

<p>
    <a asp-controller="Plot" asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<div class="table-responsive page" align="left">
    <table class="table table-hover table-dark" id="data" align="center">
        <thead>
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Area)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Coordinates)
                </th>
                <th>
                    @Html.DisplayName("Infrastructure")
                </th>
                <th scope="row"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td scope="row">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Area)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Coordinates)
                    </td>
                    <td>
                     @foreach (var item2 in item.Infrastructures.Take(3))
                    {

                            @Html.DisplayFor(modelItem => item2.Name)
                            <span>|</span>
                    }
                    </td>
                    
                    <td>
                        <a asp-controller="Plot" asp-action="Detail" asp-route-id="@item.PlotId" class="btn btn-secondary mr-2">Details</a>
                        <a asp-controller="Plot" asp-action="Edit" asp-route-id="@item.PlotId" class="btn btn-secondary mr-2">Edit</a>
                        <a asp-controller="Plot" asp-action="Delete" asp-route-id="@item.PlotId" class="btn btn-danger">Delete</a>
                       
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </br>
    <button onclick="ExportToExcel('xlsx')" class="btn btn-warning">Export table to excel</button>
</div>
<!--FOR DOWNLOADING TO EXCEL-->
<table class="table" id="export" align="center" style="display: none;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlotId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Coordinates)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WeatherConditions.SunLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WeatherConditions.WaterLevel)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PlotId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Area)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Coordinates)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WeatherConditions.SunLevel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WeatherConditions.WaterLevel)
                </td>
            </tr>
        }
    </tbody>
</table>